### PR TITLE
Features: Reload app window, Toggle full screen, Toggle dev tools

### PR DESCRIPTION
**Pull request by klauscfhq**
Hi!
Absolutely in love with the app 💓 🎉 
I took the time to organize a few already existing features like **window reload** and **dev tools toggling** and also add a **fullscreen feature** that might be useful! 

At a glance:

- Reload focused app window  
  - **Windows/Linux** <kbd>Ctrl</kbd> + <kbd>R</kdb>
  - **MacOS**  <kbd>Cmd</kbd> + <kbd>R</kdb>

- Toggle the app in and out of the full screen mode
  -  **Windows/Linux** <kbd>F11</kbd>
  - **MacOS**  <kbd>Cmd</kbd> + <kbd>F</kdb>

- Toggle dev tools alongside of the app
  -  **Windows/Linux** <kbd>Alt</kbd> + <kbd>Ctrl</kbd> +  <kbd>I</kbd>
  - **MacOS**  <kbd>Alt</kbd> + <kbd>Cmd</kbd> +  <kbd>I</kbd>

🚀 Tested on Windows 10 Pro, Linux Ubuntu 16.04 & Mac OS Sierra!

📷 Here are a few shots running the windows build!

## Menu overview

view-menu-demo

## Dev tools toggled

dev-tool-demo

## Toggling in and out of the full screen mode

full-screen-demo

### CODE REVIEW

**Comment by 1000ch** [comment]
@klauscfhq Great works 👏

**Comment by vitorgalvao** [comment]
I like your background image, @klauscfhq. What were your search terms for it?

**Comment by klauscfhq** [comment]
@vitorgalvao I randomly stumbled upon it on [unsplash](https://unsplash.com/photos/hwLAI5lRhdM?__hsfp=998628806&__hssc=187839095.1.1487462400065&__hstc=187839095.516c33848bb94ef1ea8a058478ae7e86.1487462400062.1487462400063.1487462400064.1), it's by [Clay Banks](https://unsplash.com/@claybanks1989)
Definity one of the best shots of urban Tokyo that I have ever seen. Absolutely must visit that store 😄

**Comment by vitorgalvao** [comment]
@klauscfhq Thank you. Looks great as a Trello background.

**Pull request merged**
